# Generated by Django 4.0.6 on 2022-12-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useralbum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='用戶密碼'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usermail',
            field=models.EmailField(max_length=100, verbose_name='用戶信箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用戶名稱'),
        ),
    ]
